### ISSUE TITLE
Add validation for `controller` in `ZcapClient.delegate` API

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/ezcap#15]
https://github.com/digitalbazaar/ezcap/blob/main/lib/ZcapClient.js#L124-L125

`controller` is documented as a required parameter.  However presently, if controller is not passed, the code with generate a zcap without a controller.

If `controller` is required, it should be validated appropriately.

**Comment by dlongley** [comment]
Addressed by #16.
